spring:
  application:
    name: routeresq-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
